set nofixeol
set nofixendofline
set nocompatible              " be iMproved, required
filetype off                  " required

" use this to setup vundle: git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" " plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" " Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" " git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" " The sparkup vim script is in a subdirectory of this repo called vim.
" " Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" " Install L9 and avoid a Naming conflict if you've already installed a
" " different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
" Plugin 'jceb/vim-orgmode'
Plugin 'cormacrelf/vim-colors-github'
" Plugin 'junegunn/fzf', { 'do': { -> fzf#install() } }
" Plugin 'junegunn/fzf.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

"set nowrap
set nofoldenable
autocmd WinEnter,WinLeave,BufCreate,BufEnter,BufLeave,BufNew * set nofoldenable
set background=light
set backspace=indent,eol,start
set cindent
set guioptions=agit
set hidden
set hlsearch
set colorcolumn=100
set errorformat&
set ff=unix
set ignorecase
set incsearch
set langmap=ч`,ю\\\\,ш[,щ],яq,вw,еe,рr,тt,ъy,уu,иi,оo,пp,аa,сs,дd,фf,гg,хh,йj,кk,лl,зz,ьx,цc,жv,бb,нn,мm,Ч~,Ю\|,Ш{,Щ},ЯQ,ВW,ЕE,РR,ТT,ЪY,УU,ИI,ОO,ПP,АA,СS,ДD,ФF,ГG,ХH,ЙJ,КK,ЛL,ЗZ,ЬX,ЦC,ЖV,БB,НN,МM
set laststatus=2
set linespace=3
set mouse=
set mousehide
set number
"set nonumber
set novisualbell
set ruler
set shiftwidth=4
set smartcase
set t_vb=
set tabstop=4
"ignore case for buffer/file names
set wildignorecase

"disable autocommenting on new line
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
"disable visual bell
autocmd GUIEnter * set vb t_vb=
"colorscheme default
"colorscheme desert
if &term=~'linux'
" This is the console on linux. I don't know for FreeBSD
" set your console settings here.
elseif &term=~'xterm'
    if has("gui_running")
        " Put your settings for X11 mode here
        colorscheme github
    endif
else
    colorscheme github
endif
"syntax off
syntax on
autocmd! bufreadpost *.yml set syntax=off

let g:airline_powerline_fonts = 1
let g:airline_theme='badwolf' "cant be seen in desert vim theme
"let g:airline_theme='aurora'

let g:hostname = substitute(system("hostname"), "\n", "", "")
let g:osname = substitute(system("uname -o"), "\n", "", "")
let s:haveReadSession = 0

if g:osname == "Cygwin" || g:osname == "Msys"
    let g:isWindows=1
else 
    let g:isWindows=0
endif

if g:osname == "Msys"
    set grepprg=grep
endif

"let s:user = "ivaila"
"let s:user = "stoiko"

let g:projectName = $ZPROJ
"let g:projectName = "dmd"

if g:projectName == "zhost"
    set expandtab
    let s:homeDir = "~/work/github/zhost"
    let s:appToRun = "zhost_dbg"
    let s:ctagsDirs = ""
elseif g:projectName == "bms"
    set expandtab
    let s:homeDir = "~/work/BMS/BMS_PIC24FJ256GA704.X"
    let s:appToRun = "xxx"
    let s:ctagsDirs = ""
elseif g:projectName == "intellics"
    set noexpandtab
    let s:homeDir = "~/work/DoorsNG"
    let s:appToRun = "xxx"
    let s:ctagsDirs = ""
elseif g:projectName == "bgg"
    set expandtab
    let s:homeDir = "~/work/github/bgg"
    let s:appToRun = "bgg_dbg"
    let s:ctagsDirs = "../zhost"
elseif g:projectName == "tetris"
    set expandtab
    let s:homeDir = "~/work/github/tetris"
    let s:appToRun = "tetris_dbg"
    let s:ctagsDirs = "../zhost"
elseif g:projectName == "bare_doom"
    set expandtab
    let s:homeDir = "~/work/github/bare_doom"
    let s:appToRun = "bd_dbg"
    let s:ctagsDirs = "../zhost"
elseif g:projectName == "zps2"
    set expandtab
    let s:homeDir = "~/work/github/zps2"
    let s:ctagsDirs = "../zhost"
elseif g:projectName == "brickslam"
    set expandtab
    let s:homeDir = "~/work/github/brickslam"
    let s:ctagsDirs = "../zhost"
    let s:appToRun = "brickslam_dbg"
elseif g:projectName == "visteon_sim"
    set expandtab
    let s:homeDir = "~/work/visteon/simulator"
    "let s:homeDir = "~/work/visteon/gs_redesign/fpk10_simulator/"
    let s:ctagsDirs = ""
elseif g:projectName == "visteon"
    set expandtab
    "let s:homeDir = "~/work/visteon/tools/Demos/MP22_MQBAB_IC_Basic8__CW105"
    let s:homeDir = "~/work/visteon/tools/Demos/MP22_MQBAB_IC_Basic8__CW105/programs/vw/my2022/fpkb8/vp-apps/gs"
    let s:ctagsDirs = ""
elseif g:projectName == "visteon_platform"
    set expandtab
    let s:homeDir = "~/work/visteon/platform_v8.3"
    let s:ctagsDirs = ""
elseif g:projectName == "visteon_demo"
    set expandtab
    "let s:homeDir = "~/work/visteon/MP22_FPK_Basic8"
    let s:homeDir = "~/work/visteon/fpk8_demo"
    let s:ctagsDirs = ""
elseif g:projectName == "zpsx"
    set expandtab
    let s:homeDir = "~/work/github/zpsx"
    let s:ctagsDirs = ""
    let s:appToRun = "zpsx_dbg"
    set textwidth=100
    set colorcolumn=+1        " highlight column after 'textwidth'
    "set colorcolumn=+1,+2,+3  " highlight three columns after 'textwidth'
    highlight ColorColumn ctermbg=lightgrey guibg=black
elseif g:projectName == "vreck2d"
    set expandtab
    let s:homeDir = "~/work/github/vreck2d"
    let s:ctagsDirs = ""
    let s:appToRun = "vreck2d"
elseif g:projectName == "vrexel"
    set expandtab
    let s:homeDir = "~/work/github/vrexel"
    let s:ctagsDirs = ""
    let s:appToRun = "vrexel"
elseif g:projectName == "celofanche"
    set expandtab
    let s:homeDir = "~/work/github/celofanche"
    let s:ctagsDirs = ""
    let s:appToRun = "celofanche"
    set colorcolumn=100
elseif g:projectName == "turmoil"
    set expandtab
    set errorformat=\ %#%f(%l\\,%c):\ %m
    set colorcolumn=100
    let s:homeDir = "~/work/github/turmoil/Code"
    let s:ctagsDirs = ""
elseif g:projectName == "qonche"
    set expandtab
    let s:homeDir = "~/work/github/qonche"
    let s:ctagsDirs = ""
    let s:appToRun = "qonche"
    set colorcolumn=100
elseif g:projectName == "ps2host"
    set expandtab
    let s:homeDir = "~/work/github/ps2hacking/zloedi/ps2host"
    let s:ctagsDirs = "~/work/github/ps2hacking/zloedi/zh ~/work/github/ps2hacking/zloedi/kernel"
    let s:appToRun = "ps2host"
    set colorcolumn=100
elseif g:projectName == "zs"
    set expandtab
    let s:homeDir = "~/work/github/zhost_scratch"
    let s:ctagsDirs = "../zhost"
    let s:appToRun = "zs_dbg"
elseif g:projectName == "zcom" || g:projectName == "zcom_rc"
    set noexpandtab
    set errorformat=\ %#%f(%l\\\,%c):\ %m
    " use quotes
    let s:ctagsDirs = "\"../../NativePlugins/NativeSnapShot/unity_dlls\" \"../../NativePlugins/NativeSnapShot/libs/level5/tacticalmap\" \"../Shaders\" \"../Extensions/Boxify\" \"../Users/Stoiko/code\""
    let s:additionalSVNDirs = s:ctagsDirs
elseif g:projectName == "boxify"
    set noexpandtab
    set errorformat=\ %#%f(%l\\\,%c):\ %m
    "let s:ctagsDirs = "."
    let s:additionalSVNDirs = ""
elseif g:projectName == "chaos_client" 
    set colorcolumn=100
    set noexpandtab
    set errorformat=\ %#%f(%l\\\,%c):\ %m
    " use quotes
    let s:additionalSVNDirs = "\"../Scenes\" \"../Resources_Raw\" \"../Resources\""
elseif g:projectName == "chaos_server"
    set colorcolumn=100
    set noexpandtab
    set errorformat=\ %#%f(%l\\\,%c):\ %m
    let s:additionalSVNDirs =  " \"../ChaosUnity/Assets/Scripts/ServerAndClient\" \"../ChaosUnity/Assets/Editor/Build\" "
elseif g:projectName == "kronos"
    set expandtab
    set colorcolumn=100
    set errorformat=\ %#%f(%l\\,%c):\ %m
    let s:homeDir = "/cygdrive/c/kronos/KronosUnity/Assets/Script"
    let s:ctagsDirs = " \"../AssemblyDefinitions\" \"../../Rulebase\" \"../SGLibs\" \"../ThirdParty/FFSNet\" \"../ThirdParty/AsmodeeNet\" \"../ThirdParty/ZloediUtils\" \"../ThirdParty/I2/Localization/Scripts\" \"../Editor\" \"../StreamingAssets\" \"../ThirdParty/Ludiq/Ludiq.Chronos/Source\" "
                
    let s:additionalSVNDirs = s:ctagsDirs
elseif g:projectName == "wurst"
    set expandtab
    set colorcolumn=100
    set errorformat=\ %#%f(%l\\,%c):\ %m
    let s:homeDir = "~/work/github/wurst/Code"
    let s:ctagsDirs = ""
    let s:appToRun = "../Build/Wurst"
elseif g:projectName == "radical_rumble"
    set expandtab
    set colorcolumn=100
    set errorformat=\ %#%f(%l\\,%c):\ %m
    let s:homeDir = "~/work/github/radical_rumble/Code"
    let s:ctagsDirs = ""
    let s:appToRun = "../BuildSDL/game_sdl"
elseif g:projectName == "pp_tactics"
    set expandtab
    set colorcolumn=100
    set errorformat=\ %#%f(%l\\,%c):\ %m
    let s:homeDir = "~/work/github/pp_tactics/Code"
    let s:ctagsDirs = ""
    let s:appToRun = "../pp_located_somewhere"
elseif g:projectName == "csharp_sdl"
    set expandtab
    set colorcolumn=100
    set errorformat=\ %#%f(%l\\,%c):\ %m
    let s:homeDir = "~/work/github/csharp_sdl_skeleton/Code"
    let s:ctagsDirs = ""
    let s:appToRun = "../BuildSDL/game_sdl"
elseif g:projectName == "dmd"
" 'dmd' assumes native windows (osname=Msys) version of gVim
    set expandtab
    set colorcolumn=100
    set errorformat=\ %#%f(%l\\,%c):\ %m
    let s:homeDir = "/dmd_win/DeathMustDie/Assets/Editor/Zloedi/.assembly_src"
    let s:ctagsDirs = " \
\"../../../Scripts\" \
\"../../../Tests\" \
\"../../../Editor\" \
\"../../../../Library/PackageCache/com.claw.app@fc29704bc0\" \
\"../../../../Library/PackageCache/com.claw.core@48b048b9b5\" \
\"../../../../Library/PackageCache/com.claw.user.interface@d6aa421b64\" "
    let s:appToRun = "Build\\binaries\\Death\ Must\ Die"
elseif g:projectName == "qronos"
    set expandtab
    set colorcolumn=100
    set errorformat=\ %#%f(%l\\,%c):\ %m
    let s:homeDir = "/cygdrive/c/kronos/Qronos"
    let s:additionalSVNDirs = "../KronosUnity/"
    let s:ctagsDirs = " \
\"../KronosUnity/Assets/AssemblyDefinitions\" \
\"../KronosUnity/Rulebase\" \
\"../KronosUnity/Assets/SGLibs\" \
\"../KronosUnity/Assets/Script\" \
\"../KronosUnity/Assets/ThirdParty/FFSNet\" \
\"../KronosUnity/Assets/ThirdParty/AsmodeeNet\" \
\"../KronosUnity/Assets/ThirdParty/ZloediUtils\" \
\"../KronosUnity/Assets/ThirdParty/I2/Localization/Scripts\" \
\"../KronosUnity/Assets/StreamingAssets\" \
\"../KronosUnity/Assets/ThirdParty/Ludiq/Ludiq.Chronos/Source\" \
\"../KronosUnity/Assets/zloedi\" "
    let s:appToRun = "../Build/Kronos"
elseif g:projectName == "viking"
    set expandtab
    set colorcolumn=100
    set errorformat=\ %#%f(%l\\,%c):\ %m
    let s:homeDir = "~/work/github/VikingVillage/Code"
    let s:ctagsDirs = ""
    let s:appToRun = "../Build/VikingVillage"
elseif g:projectName == "SDLApp"
    set expandtab
    set colorcolumn=100
    set errorformat=\ %#%f(%l\\,%c):\ %m
    let s:homeDir = "~/work/SDLApp"
    let s:ctagsDirs = ""
    let s:appToRun = "SDLApp"
elseif g:projectName == "BragDoll"
    set expandtab
    set colorcolumn=100
    set errorformat=\ %#%f(%l\\,%c):\ %m
    let s:homeDir = "~/work/BragDoll/Code"
    let s:ctagsDirs = ""
    let s:appToRun = "../build/BragDoll"
elseif g:projectName == "raypunk"
    set expandtab
    set colorcolumn=100
    set errorformat=\ %#%f(%l\\,%c):\ %m
    let s:homeDir = "~/work/github/raypunk/Code"
    let s:ctagsDirs = "../Build/raypunk"
    let s:appToRun = "../Build/Game"
elseif g:projectName == "gallium_github"
    set expandtab
    set colorcolumn=100
    set errorformat=\ %#%f(%l\\\,%c):\ %m
    let s:additionalSVNDirs = ""
    let s:homeDir = "/cygdrive/c/gallium_github/Game"
	let s:appToRun = "../Build/Gallium"
elseif g:projectName == "alt_server"
    set expandtab
    set colorcolumn=100
    set errorformat=\ %#%f(%l\\\,%c):\ %m
    let s:additionalSVNDirs = ""
else
    let s:additionalSVNDirs = ""
    set expandtab
endif

if g:hostname == "monster"
    set guifont=Ubuntu\ Mono\ derivative\ Powerline\ 12
    "set guifont=Droid\ Sans\ Mono\ 9
    "set guifont=Inconsolata\ 8 
elseif g:hostname == "acer-laptop"
    if g:osname == "Msys"
        set guifont=Source_Code_Pro:h14:cANSI:qDRAFT
    else
        set guifont=Space\ Mono\ for\ Powerline\ 14
    endif
elseif g:hostname == "Zammy-Gaming" 
    if g:osname == "Msys"
        set guifont=Source_Code_Pro:h11:cANSI:qDRAFT
    elseif g:osname == "Cygwin"
        set guifont=Space\ Mono\ for\ Powerline\ 11
    else
        set guifont=Space_Mono_for_Powerline:h11
    endif
elseif g:hostname == "DESKTOP-TD3AU4V"
    "set guifont=Space\ Mono\ for\ Powerline\ 14
    set guifont=Space\ Mono\ for\ Powerline\ 14
elseif g:hostname == "DESKTOP-JUGNII1"
    set guifont=Ubuntu\ Mono\ derivative\ Powerline\ 12
elseif g:hostname == "laptop"
    set guifont=Ubuntu\ Mono\ derivative\ Powerline\ 11
    "set guifont=Inconsolata\ 9 
elseif g:hostname == "Phoenix"
    "set guifont=Lucida\ Console\ Semi-Condensed\ 10
    set guifont=Inconsolata\ Medium\ 10
    "set lines=90
elseif g:hostname == "SNAPSHOT-STOIKO"
    "set guifont=DejaVu\ Sans\ Mono\ for\ Powerline\ Medium\ 10
    set t_md=
    set guifont=Inconsolata\ Medium\ 10
    "set guifont=Inconsolata\ for\ Powerline\ Medium\ 11
    "set guifont=Ubuntu\ Mono\ derivative\ Powerline\ Medium\ 11
    "set guifont=Meslo\ LG\ L\ DZ\ for\ Powerline\ 10
    "set vb 
elseif g:hostname == "monster-win"
    "set guifont=DejaVu\ Sans\ Mono\ for\ Powerline\ 8
    "set guifont=Inconsolata\ Medium\ 11
    set guifont=Ubuntu\ Mono\ derivative\ Powerline\ 12
else
    if g:osname == "Msys"
        set guifont=Source_Code_Pro:h11:cANSI:qDRAFT
    else
        set guifont=Space\ Mono\ for\ Powerline\ 11
    endif
endif

function! CTags_f( ... )
    execute "cd " . a:1
    execute "!ctags -R \"" . a:2 . "/\"" . " " . s:ctagsDirs
endfunction

function! Build_f( ... )
    if ! g:isWindows
        execute "!killall xterm" 
    endif

    wall

    execute "cd " . a:1
    if ! s:haveReadSession
        execute "source vim_session" . "_" . g:projectName
        let s:haveReadSession = 1
    endif

    if g:projectName == "bms_doors" || g:projectName == "bms"
        execute "make -f " . a:2 . "/cygwin/Makefile-cygwin"
    elseif g:projectName == "dmd"
        if g:osname == "Cygwin"
            execute "make -f " . a:2 . "/Makefile_cygwin "
        else
            execute "make -f " . a:2 . "/Makefile_mingw "
        endif
    elseif a:0 == 2
        execute "make -f " . a:2 . "/Makefile "
    elseif a:0 == 3
        execute "make -f " . a:2 . "/Makefile " . a:3
    elseif a:0 == 4
        execute "make -f " . a:2 . "/Makefile " . a:3 . " " . a:4
    else
        echo "Num of args not supported"
    endif

    if g:projectName == "chaos_client"
        execute "!ctags -R " . a:2
    elseif g:projectName == "chaos_server" || g:projectName == "alt_server" || g:projectName == "gallium_github"
        execute "!ctags -R " . a:2 . s:additionalSVNDirs
"    elseif g:projectName == "pcsx2"
"        execute "!ctags -R " . a:2 . "/" . " " . s:additionalSVNDirs
    elseif g:projectName == "visteon" || g:projectName == "visteon_sim" || g:projectName == "visteon_platform" || g:projectName == "visteon_demo"
    elseif g:projectName == "qronos" || g:projectName == "dmd"
    elseif g:projectName != ""
        execute "!ctags -R \"" . a:2 . "/\"" . " " . s:ctagsDirs
    else 
        execute "!ctags -R " . a:2 . " " . "engine"
    endif

    execute "mksession! vim_session" . "_" . g:projectName
endfunction

function! Run_f( ... )
    if g:projectName == "dmd"
        let pathToExe = a:1 . "\\" . a:2 . "\\" . a:3
        execute "!start /b \"" . pathToExe . ".exe\""
    else
        call Build_f( a:1, a:2, a:3 )

        let pathToExe = a:1 . "/" . a:2 . "/" . a:3

        if g:isWindows
            execute "!" . pathToExe . ".exe&"
        else
            execute "!killall xterm ; xterm -e \"" . pathToExe . "\"&"
        endif
    endif
endfunction

function! FindInFiles_f( ... )
    let cmdPref = "grep -nriIe \""
    let cmdSuf = " --exclude-dir=*{.git,.svn,doxygen} --exclude=*{tags,vim_session*} --exclude=*.{csproj,config,xml,html,mk,o,d,map,tst,txt} --include=*.{cfg,lvl,c,cs,md,cpp,h,lua,asm,cmake,csv}" 
    if a:0 == 1 
        execute cmdPref . a:1 . "\" . " . s:ctagsDirs . cmdSuf
    elseif a:0 == 2 
        execute cmdPref . a:1 . "\" \"" . a:2 . "\" " . cmdSuf
    elseif a:0 == 3 
        execute cmdPref . a:1 . "\" " . a:2 . " " . a:3 . " " . cmdSuf
    elseif a:0 == 4 
        execute cmdPref . a:1 . "\" \"" . a:2 . "\" \"" . a:3 . "\" \"" . a:4 . "\" " . cmdSuf
    elseif a:0 == 5 
        execute cmdPref . a:1 . "\" \"" . a:2 . "\" \"" . a:3 . "\" \"" . a:4 . "\" \"" . a:5 . "\" " . cmdSuf
    elseif a:0 == 6 
        execute cmdPref . a:1 . "\" \"" . a:2 . "\" \"" . a:3 . "\" \"" . a:4 . "\" \"" . a:5 . "\" \"" . a:6 . "\" " . cmdSuf
    elseif a:0 == 7 
        execute cmdPref . a:1 . "\" \"" . a:2 . "\" \"" . a:3 . "\" \"" . a:4 . "\" \"" . a:5 . "\" \"" . a:6 . "\" \"" . a:7 . "\" " . cmdSuf
    else
        echo "Num of args not supported"
    endif
endfunction

function! SvnBlame()
   let line = line(".")
   setlocal nowrap
   " blame, ignoring white space changes
   !/bin/svn blame "%" -x-w "%" > /tmp/SVNblame_vim
   18 vsplit! /tmp/SVNblame_vim
   e /tmp/SVNblame_vim
   setlocal nomodified nowrap winwidth=1
   setlocal nonumber
   if has('&relativenumber') | setlocal norelativenumber | endif
   " return to original line
   exec "normal " . line . "G"
   " synchronize scrolling, and return to original window
   setlocal scrollbind
   wincmd p
   setlocal scrollbind
   syncbind
endfunction

function! SvnBlameOff()
   bd /tmp/SVNblame_vim
   setlocal noscrollbind
   setlocal wrap
endfunction

command! -nargs=+ FindInFiles call FindInFiles_f( <q-args>, "." )

if 0
    command! -nargs=0 Build call Build_f( "~/work/necropolis", "maria/eduworld" )
    map <F5> :Run "~/work/necropolis/maria/eduworld/eduworld_dbg" <CR>
elseif 0
    command! -nargs=0 Build call Build_f( "~/work/private", "imgui" )
    command! -nargs=0 Clean execute "!make -f ~/work/private/imgui/Makefile clean"
    command! -nargs=+ FindInFiles execute "grep -riIF -e \"" . <q-args> . "\" \"imgui\" \"engine\" --exclude-dir=.svn --exclude=tags" 
    map <F5> :Run "$HOME/work/private/imgui/imgui_dbg" <CR>
elseif g:projectName == "grid_fov"
    command! -nargs=0 Build call Build_f( "~/work/private", "grid_fov" )
    command! -nargs=0 Run call Run_f( "~/work/private", "grid_fov", "grid_fov_dbg" )
    command! -nargs=0 Clean execute "!make -f ~/work/private/grid_fov/Makefile clean"
    command! -nargs=+ FindInFiles execute "grep -riIF -e \"" . <q-args> . "\" \"grid_fov\" \"engine\" --exclude-dir=.svn --exclude=tags" 
elseif g:projectName == "laser_chess"
    command! -nargs=0 Build call Build_f( "~/work/private", "laser_chess" )
    command! -nargs=0 Run call Run_f( "~/work/private", "laser_chess", "laser_chess_dbg" )
    command! -nargs=0 Clean execute "!make -f ~/work/private/laser_chess/Makefile clean"
    command! -nargs=+ FindInFiles execute "grep -riIF -e \"" . <q-args> . "\" \"laser_chess\" \"engine\" --exclude-dir=.svn --exclude=tags" 
elseif g:projectName == "bms"
    command! -nargs=0 Build call Build_f( "~/work/BMS/BMS_PIC24FJ256GA704.X", "." )
elseif g:projectName == "bms_doors"
    command! -nargs=0 Build call Build_f( "~/work/BMSDoorPanels", "." )
elseif g:projectName == "boxify"
    if g:hostname == "monster-win" || g:hostname == "SNAPSHOT-STOIKO"
        command! -nargs=0 Build call Build_f( "~/work/boxify/Assets/Scripts",
                    \ ".", 
                    \ "PATH_TO_SCRIPT=\"~/work/snapshot/trunk/PhoenixPoint/Unity/PhoenixPointUnity/Assets/Users/Stoiko/code/cygwin_compile.sh\"",
                    \ "PATH_TO_MSBUILD=\"/cygdrive/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/BuildTools/MSBuild/15.0/Bin/MSBuild.exe\"")
    elseif g:hostname == "monster"
        command! -nargs=0 Build call Build_f( "/home/stoiko/work/chaos/trunk/PhoenixPoint/Unity/PhoenixPointUnity/Assets/Code", "." )
    endif
    command! -nargs=+ FindInFiles call FindInFiles_f( <q-args> )
"elseif g:projectName == "pcsx2"
"    if g:hostname == "SNAPSHOT-STOIKO"
"        command! -nargs=0 Build call Build_f( "/tmp/pcsx2", "." )
"    else
"        command! -nargs=0 Build call Build_f( "~/work/pcsx2-master", "." )
"    endif
elseif g:projectName == "chaos_client"
    command! -nargs=0 Build call Build_f( "/cygdrive/c/gallium/ChaosUnity/Assets/Scripts", "." )
elseif g:projectName == "chaos_server"
    command! -nargs=0 Build call Build_f( "/cygdrive/c/gallium/ChaosServer", "." )
	command! -nargs=+ FindInFiles call FindInFiles_f( <q-args>, ".", s:additionalSVNDirs )
elseif g:projectName == "alt_server"
    command! -nargs=0 Build call Build_f( "/cygdrive/c/gallium_github/Server", "." )
	command! -nargs=+ FindInFiles call FindInFiles_f( <q-args>, ".", s:additionalSVNDirs )
elseif g:projectName == "gallium_github"
    command! -nargs=0 Build call Build_f( "/cygdrive/c/gallium_github/Game", "." )
	command! -nargs=+ FindInFiles call FindInFiles_f( <q-args>, ".", s:additionalSVNDirs )
    command! -nargs=0 Run call Run_f( s:homeDir, ".", s:appToRun )
elseif g:projectName == "dmd"
    command! -nargs=0 Build call Build_f( s:homeDir, "." )
    command! -nargs=0 CTags call CTags_f( s:homeDir, "." )
    command! -nargs=0 Run call Run_f( "c:", "dmd_mint", s:appToRun )
    command! -nargs=+ FindInFiles call FindInFiles_f( <q-args>, ".", s:ctagsDirs )
elseif g:projectName != ""
    command! -nargs=0 Build call Build_f( s:homeDir, "." )
    command! -nargs=0 CTags call CTags_f( s:homeDir, "." )
    command! -nargs=0 Run call Run_f( s:homeDir, ".", s:appToRun )
    command! -nargs=+ FindInFiles call FindInFiles_f( <q-args>, ".", s:ctagsDirs )
else
    command! Build echo "Build: did you specify $ZPROJ? If yes, enable the build configuration for '" . g:projectName . "' in vimrc first"
endif

command! -nargs=0 SVNdiffoff        execute "bd /tmp/" . expand("%:t") | diffoff!
command! -nargs=0 SVNdiff           diffoff! | execute "!/bin/svn export --force \"%\" /tmp/%:t -r COMMITTED" | vert diffsplit /tmp/%:t | goto
command! -nargs=0 SVNprevX          diffoff! | execute "!/bin/svn export --force \"%\" /tmp/%:t -r PREV" | vert diffsplit /tmp/%:t | goto
command! -nargs=0 SVNdiffX          diffoff! | execute "!/bin/svn export --force \"%\" /tmp/%:t -r COMMITTED" | vert diffsplit /tmp/%:t | wincmd x | goto
command! -nargs=0 SVNprev           diffoff! | execute "!/bin/svn export --force \"%\" /tmp/%:t -r PREV" | vert diffsplit /tmp/%:t | wincmd x | goto
command! -nargs=0 SVNstatus         e /tmp/SVNstatus_vim | bd /tmp/SVNstatus_vim | execute "!/bin/svn status $(ls) " . s:additionalSVNDirs . " | sort | grep -ve ^[?I] -ve \.mat > /tmp/SVNstatus_vim" | 10split | e /tmp/SVNstatus_vim | wincmd w
command! -nargs=0 SVNstatusx        e /tmp/SVNstatus_vim | bd /tmp/SVNstatus_vim | execute "!/bin/svn status $(ls) " . s:additionalSVNDirs . " | sort | grep -ve ^[?I] -ve \.mat > /tmp/SVNstatus_vim" | 10split | e /tmp/SVNstatus_vim | wincmd w
command! -nargs=+ SVNcommitMulti    execute "!/bin/svn commit --targets /tmp/SVNstatus_vim -m \"" . <q-args> . "\"" | SVNdiffoff 
command! -nargs=+ SVNcommit         execute "!/bin/svn commit \"%\" -m \"" . <q-args> . "\"" | SVNdiffoff
command! -nargs=0 SVNblame          call SvnBlame()
command! -nargs=0 SVNblameoff       call SvnBlameOff()

command! -nargs=+ ReplaceCwordInFile execute "%s/" . expand( "<cword>" ) . "/" . <q-args> . "/g"
command! -nargs=0 Date              execute ".!date +\"\\%A \\%B \\%d \\%Y\""
command! -nargs=0 Hour              execute ".!date +\\%R" | startinsert! 

map <F3>   :FindInFiles 
map <C-F3> :ReplaceCwordInFile 
map <F8>   :Build<CR>
map <F9>   :CTags<CR> 
map <F5>   :Run<CR>
":map gb :call <SID>svnBlame()<CR>

runtime ftplugin/man.vim 

